# Generated by Django 3.0.3 on 2020-04-04 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionpapers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionbank', '0004_auto_20200404_2310'),
        ('utils', '0004_devices_licensekeys_questiontypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_id', models.CharField(max_length=10)),
                ('passkey', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Courses')),
                ('question_paper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='questionpapers.QuestionPaper')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marked', models.BooleanField(default=False)),
                ('is_submitted', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ManyToManyField(to='questionbank.Option')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionbank.SubQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utils.Devices')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examination.Exam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DynamicExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_id', models.CharField(max_length=10)),
                ('passkey', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Courses')),
                ('question_paper', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='questionpapers.QuestionPaper')),
            ],
        ),
    ]
