# Generated by Django 3.0.3 on 2020-04-03 18:14

from django.db import migrations, models
import django.db.models.deletion
import django_encrypted_filefield.fields
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0003_bloomscategory_courseoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', fernet_fields.fields.EncryptedTextField(verbose_name='question')),
                ('marks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', fernet_fields.fields.EncryptedTextField(verbose_name='question')),
                ('has_images', models.BooleanField(default=False)),
                ('marks', models.IntegerField()),
                ('has_subquestions', models.BooleanField(default=False)),
                ('is_mcq_question', models.BooleanField(default=False)),
                ('blooms_category', models.ManyToManyField(to='utils.BloomsCategory')),
                ('course_outcomes', models.ManyToManyField(to='utils.CourseOutcome')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Topics')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', fernet_fields.fields.EncryptedTextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_encrypted_filefield.fields.EncryptedImageField(upload_to='public/images/questions/')),
                ('alt_text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Question')),
            ],
        ),
    ]
