# Generated by Django 3.0.3 on 2020-04-03 18:25

from django.db import migrations, models
import django.db.models.deletion
import fernet_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_mcq_question',
        ),
        migrations.AddField(
            model_name='subquestion',
            name='is_mcq_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.SubQuestion'),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_subquestions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=fernet_fields.fields.EncryptedTextField(null=True, verbose_name='question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.Option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.SubQuestion')),
            ],
        ),
    ]
