# Generated by Django 3.0.3 on 2020-04-04 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionbank', '0004_auto_20200404_2310'),
        ('utils', '0004_devices_licensekeys_questiontypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('marks', models.IntegerField()),
                ('parts', models.IntegerField()),
                ('questions', models.IntegerField()),
                ('has_innovative', models.BooleanField()),
                ('has_casestudy', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(to='questionbank.Question')),
                ('syllabus', models.ManyToManyField(to='utils.Topics')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questionpapers.Template')),
            ],
        ),
    ]
