# Generated by Django 3.0.3 on 2020-04-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_bloomscategory_courseoutcome'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_key', models.UUIDField(unique=True)),
                ('device_limit', models.IntegerField()),
                ('college', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='utils.College')),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=64)),
                ('registered_at', models.DateTimeField(auto_now=True)),
                ('license_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.LicenseKeys')),
            ],
        ),
    ]
